# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': '\u4e3b\u9898', 'verbose_name_plural': '\u4e3b\u9898\u5217\u8868'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
