# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20180329_0108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='art',
        ),
    ]
