# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20180329_0109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
    ]
