# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20180329_0319'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table=None,
        ),
        migrations.AlterModelTable(
            name='classnum',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
