# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20180329_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.SmallIntegerField(verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.SmallIntegerField(verbose_name='\u6027\u522b'),
        ),
    ]
