# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20180329_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.CharField(default=18, max_length=200, verbose_name='\u5e74\u9f84'),
            preserve_default=False,
        ),
    ]
