# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headshot', models.ImageField(null=True, upload_to='upload/%Y/%m/%d', verbose_name='\u5934\u50cf')),
                ('username', models.CharField(max_length=25, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('gender', models.SmallIntegerField(verbose_name='\u6027\u522b')),
                ('age', models.DateTimeField(verbose_name='\u51fa\u751f\u5e74\u6708')),
            ],
        ),
    ]
