# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_auto_20180407_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_01',
            name='gender',
            field=models.CharField(max_length=25, verbose_name='\u6027\u522b'),
        ),
    ]
