# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_auto_20180407_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_01',
            name='age',
            field=models.CharField(max_length=25, verbose_name='\u51fa\u751f\u5e74\u6708'),
        ),
    ]
