# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_auto_20180407_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_01',
            old_name='age',
            new_name='_age',
        ),
        migrations.RenameField(
            model_name='user_01',
            old_name='gender',
            new_name='_gender',
        ),
    ]
