# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20180407_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_01',
            name='_age',
        ),
        migrations.AddField(
            model_name='user_01',
            name='_csAge',
            field=models.CharField(default=1, max_length=25, verbose_name='\u51fa\u751f\u5e74\u6708'),
            preserve_default=False,
        ),
    ]
