# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_auto_20180407_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_01',
            old_name='_csAge',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user_01',
            old_name='_gender',
            new_name='gender',
        ),
    ]
