# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_auto_20180408_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_01',
            name='password1',
            field=models.CharField(default=1, max_length=50, verbose_name='\u91cd\u590d\u5bc6\u7801'),
            preserve_default=False,
        ),
    ]
