# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_user_01_password1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'ordering': ['-id'], 'permissions': (('view_Article', '\u67e5\u770b\u4e66\u7c4d'), ('update_Article', '\u4fee\u6539\u4e66\u7c4d'), ('del_Article', '\u5220\u9664\u4e66\u7c4d')), 'verbose_name': '\u4e3b\u9898', 'verbose_name_plural': '\u4e3b\u9898\u5217\u8868'},
        ),
    ]
